### ISSUE TITLE
Garry's Mod update 15-03-09

### ISSUE THREAD

**Issue by F0x06** [pixeltailgames/elevator-source#3]
Hi, can you fix the gamemode for the latest game version ? 
See: http://www.garrysmod.com/2015/03/09/15-03-09/

There is a lot of errors due to some lua changes,
cheers, and thanks in advance, F0x

**Comment by samuelmaddock** [comment]
I'll take a look at it this weekend.

**Comment by samuelmaddock** [comment]
@F0x06 Would you be able to post the Lua errors you're having? I'm not seeing any while testing.

**Comment by F0x06** [comment]
@samuelmaddock Hi, i re-started my server today and for now i have no errors, except some camera view teleports/frezzes, i reinstalled it using the github version with the contents of the workshop addon, i will make more tests to confirm you if there is a problem anymore, i will close the issue when its done, cheers, F0x

**Comment by F0x06** [comment]
@samuelmaddock All is working great apparently, verry strange issue, sorry for that
Cheers, F0x
